### ISSUE TITLE
Missing release and license

### ISSUE THREAD

**Issue by fabioasdias** [ppalyafari/grafana-movingtemplatevariables#1]
Hi,

first, thanks for the contribution, this is rather useful. However, I can't use it without a license and "official" releases on the repo. Could those please be added?

**Comment by ppalyafari** [comment]
Hi, I've created a release, and I think the default LICENSE file that is generated by Grafana when creating a new plugin is also there, but let me know if you need something else.

**Comment by fabioasdias** [comment]
Hi, appreciate the quick turn around.

I see the apache LICENSE file on the subfolder, however since it isn't on the root, github doesn't recognize it as applicable to the whole repo/component, so it doesn't show on the description of the repo (the fields on the right when one lands on the code). That means that automated tools won't pick it up either.  It would default to closed source for most OSS management tools and be blocked...

**Comment by ppalyafari** [comment]
Hi, you are right, I missed that. I restructured the repo and made a new release.

**Comment by wkneewalden** [comment]
Making note that when I tested the plugin I found that grafana-movingtemplatevariables-1.0.0.zip did not work, I had to use the zip inside called ppalyafari-movingtemplatevariables-panel.zip in the Grafana plugin folder. I assume that since ppalyafari-movingtemplatevariables-panel.zip is included as part of grafana-movingtemplatevariables-1.0.0.zip then it might be ok still if the later is used in the release.
